### ISSUE TITLE
Models / Interfaces are missing from the global import path

### ISSUE THREAD

**Issue by rkodev** [microsoftgraph/msgraph-sdk-typescript#106]
Sample object missing in the global barrels File

Sample Link : https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&tabs=go

Actual

```typescript

import { BatchRecordDecisionsPostRequestBody } from '../models';

```

Expected 

```typescript

import { BatchRecordDecisionsPostRequestBody } from '../identityGovernance/accessReviews/definitions/item/instances/item/batchRecordDecisions/batchRecordDecisionsPostRequestBody';

```

**Comment by rkodev** [comment]
issue discussed here https://github.com/microsoft/kiota/discussions/1574

**Comment by baywet** [comment]
@rkodev I'm not sure I follow what the issue was here, can you provide more context please?

**Comment by baywet** [comment]
additional ping for @rkodev here

**Comment by rkodev** [comment]
Closing this as its no longer needed after package split
