### ISSUE TITLE
Missing Path Parameter - (Not Present in CSDL)

### ISSUE THREAD

**Issue by rkodev** [microsoftgraph/msgraph-sdk-typescript#108]
Path parameters are missing from the CSDL but present in snippets

Sample Link : https://docs.microsoft.com/en-us/graph/api/accessreviewinstance-batchrecorddecisions?view=graph-rest-beta&tabs=typescript

`pendingAccessReviewInstancesById` is missing from `MeRequestBuilder`
```typescript

const authProvider = new AzureIdentityAuthenticationProvider(new ClientSecretCredential("tenantId", "clientId", "clientSecret")); 


//THIS SNIPPET IS A PREVIEW FOR THE KIOTA BASED SDK. NON-PRODUCTION USE ONLY
const graphServiceClient = GraphServiceClient.init({authProvider});

const requestBody : BatchRecordDecisionsPostRequestBody = {
	decision : "Approve",
	justification : "All principals with access need continued access to the resource (Marketing Group) as all the principals are on the marketing team",
	resourceId : "a5c51e59-3fcd-4a37-87a1-835c0c21488a",
};

async () => {
	await graphServiceClient.me.pendingAccessReviewInstancesById("accessReviewInstance-id").batchRecordDecisions.post(requestBody);
}

```

**Comment by baywet** [comment]
closing as this is present in beta
https://github.com/microsoftgraph/msgraph-beta-sdk-typescript/blob/247adb8878eb8c165a72c2113d1f5c0044f4dddb/packages/msgraph-beta-sdk-users/users/item/pendingAccessReviewInstances/item/batchRecordDecisions/index.ts#L43

And the me binding is covered by #472
