### ISSUE TITLE
src contains older files causing compilation errors

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/msgraph-sdk-typescript#24]
Expected: Auto generated process must deleted the generated src code and check in the newly generated files.
Actual: The auto generated code is not deleting the older irrelevant files.

**Comment by nikithauc** [comment]
@rkodev  this is resolved right?

**Comment by rkodev** [comment]
@nikithauc Yes, this has been resolved by this [PR](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/709)
