### ISSUE TITLE
Package install in Raptor

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/msgraph-sdk-typescript#491]

**Comment by rkodev** [comment]
@sebastienlevert @andrueastman could you share some more information on this issue

**Comment by andrueastman** [comment]
@rkodev I'm not clear on this one. I'd suggest holding this one off for now till at least Seb gets back to get clarity on outcomes and priority....

**Comment by baywet** [comment]
I'm pretty sure he meant to capture the fact we need to support the package installation in Raptor as the API surface is now divided across multiple packages.

**Comment by baywet** [comment]
closing as duplicate of this issue. https://github.com/microsoftgraph/msgraph-sdk-typescript-core/issues/13

**Comment by rkodev** [comment]
Closed by https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/3600
