### ISSUE TITLE
Fix release pipeline issue

### ISSUE THREAD

**Issue by koros** [microsoftgraph/msgraph-sdk-typescript#575]
Use Vtest for testing: https://vitest.dev/

**Comment by baywet** [comment]
@koros was that initially to cover the es6 modules breakage? If so can we close it?
If not, and we want to migrate to vitest instead of the current testing infrastructure, may I suggest remaining the issue with something more explicit?

**Comment by koros** [comment]
Yeah the issue got addressed by the migration to es6
