### ISSUE TITLE
[Docs] Provide complete example of authProvider creation.

### ISSUE THREAD

**Issue by 1oglop1** [microsoftgraph/msgraph-sdk-typescript#627]
[This documentation](https://github.com/microsoftgraph/msgraph-sdk-typescript?tab=readme-ov-file#31-get-users-detailed-information) ( link from )  https://github.com/microsoftgraph/msgraph-sdk-typescript/blob/6c55abb9b6593687899111f92c5f914eb8fd3fe8/README.md?plain=1#L32

Shows incomplete an example and delegates the creation of `authProvider` to another page showing `authProvider` from the old SDK, the link should be removed and documentation updated with a complete example showing the initialization of `authProvider` from this SDK. 
It may also be useful to mention that they are not compatible.

more context: #479

**Comment by baywet** [comment]
Note; the changes will need to be replicated to core and beta as well.

**Comment by baywet** [comment]
authored #628
